name: test workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch


#TODO 
  # add cache
  # setup env vars

on:
  #schedule:
   # - cron: '* * * * *'
  workflow_dispatch:

permissions:
      id-token: write
      contents: read    # This is required for actions/checkout@v2


env:
  python-version: 3.7


jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
    - name: PR checkout
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.python-version }}

    - uses: actions/cache@master
      id: cache
      with:
        path: ${{ env.pythonLocation}}/lib/python${{ env.python-version }}/site-packages/*
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

    - name: Install requirements
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
          echo "Installing dependencies and caching them."
          pip install -r requirements.txt
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          role-to-assume: arn:aws:iam::420737321821:role/CUSPFE-SageMakerExecutionRole-oidc
          role-session-name: samplerolesession
          aws-region: 'us-east-1'
    
    - name: Fire SageMaker
      id: sm_train
      run: |
        #aws s3 lsname: test workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch


#TODO 
  # add cache
  # setup env vars

on:
  #schedule:
   # - cron: '* * * * *'
  workflow_dispatch:

permissions:
      id-token: write
      contents: read    # This is required for actions/checkout@v2


env:
  python-version: 3.7


jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
    - name: PR checkout
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.python-version }}

    - uses: actions/cache@master
      id: cache
      with:
        path: ${{ env.pythonLocation}}/lib/python${{ env.python-version }}/site-packages/*
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

    - name: Install requirements
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
          echo "Installing dependencies and caching them."
          pip install -r requirements.txt
    
    - name: Fire SageMaker
      id: sm_train
      run: |
        #aws s3 ls
